41 add tests
forumone/socrata pull request #59
Opened 2017-02-03 23:38 UTC by blakestein

Merge tests for socrata and socrata_filter modules.

2017-02-06 19:16 UTC, PapaGrande requested changes

2017-02-06 19:16 UTC, PapaGrande commented on src/Entity/Endpoint.php
> -/**
Why was this removed?

2017-02-06 19:16 UTC, PapaGrande commented on config/schema/socrata.schema.yml
> -  type: mapping
Can you explain this change?

2017-02-06 19:16 UTC, PapaGrande commented on socrata_filter/tests/src/Kernel/FilterSocrataTest.php
> +    ];
Would it make sense to put this info into an easily-editable generic YML file for use by all tests?

Like https://www.drupal.org/docs/8/creating-custom-modules/add-a-default-configuration.

Then we can have instances such as "goodURL" and "badURL" for testing.

2017-02-06 19:16 UTC, PapaGrande commented on tests/src/Unit/EndpointTest.php
> +    $this->assertEquals('rn6u-vkuv', $components['dataset_id']);
This could be parsed out of the URL with RegEx instead of being hardcoded.

2017-02-06 20:06 UTC, blakestein commented on src/Entity/Endpoint.php
> -/**
Code sniffer said namespaced files should not start with a file doc comment.

2017-02-06 20:18 UTC, blakestein commented on config/schema/socrata.schema.yml
> -  type: mapping
It was my understanding that this YAML was for a configuration object, which has a subtype that should be used

> There are two types that configuration schema predefines for configuration files: config_object for global configuration files and config_entity for entities.

https://www.drupal.org/docs/8/api/configuration-api/configuration-schemametadata

2017-02-06 22:03 UTC, blakestein commented on socrata_filter/tests/src/Kernel/FilterSocrataTest.php
> +    ];
I moved config to a YAML file in a /tests/config dir in the main module. I don't think the /config/install dir would be appropriate, nor using the config API, I think that's really for module settings configuration.

2017-02-09 23:13 UTC, PapaGrande approved these changes

2017-02-09 23:14 UTC, PapaGrande commented
@blakestein Can you resolve the merge conflicts?

2017-02-10 01:21 UTC, merged